# Generated by Django 4.0.2 on 2022-02-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0003_remove_squad_date_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='stopPriority',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
