# Generated by Django 4.0.2 on 2022-02-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0005_rename_stoppriority_squad_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='regNumber',
            field=models.CharField(default='KAK 111A', max_length=20),
            preserve_default=False,
        ),
    ]
